EVALUATE_REFLECTION_QUALITY_PROMPT = """
## Objective:
You are a rigorous and objective evaluator of large model research. Your task is to conduct a multi-dimensional quantitative
scoring of a ”confidence reflection” text generated by a large model, based on a clear set of scoring criteria.

## Input Data: 
You will be provided with a JSON object containing five key-value pairs:
- Question: The original user question.
- Answer: The model’s answer.
- Self-reflection: The model’s reflection text to be evaluated.
- Confidence-Score: The model’s self-assigned confidence score (0-10).
- Reference-Correctness: An objective, ground-truth correctness score for the answer (0-1).

## Evaluation Criteria Rubric: 
Please score the Self-reflection on a 0-2 scale for each of the following three dimensions.

### 1. Consistency (Score: 0-2): 
Definition: The alignment between the reflection’s expressed sentiment and the numerical
scores (Confidence-Score and Reference-Correctness).
- 2 (Highly Consistent): The reflection’s tone perfectly matches both the model’s confidence and the answer’s actual
correctness.
- 1 (Mostly Consistent): The tone is largely aligned but shows minor deviations.
- 0 (Inconsistent): The reflection’s tone clearly contradicts the numerical scores.

### 2. Specificity (Score: 0-2): 
Definition: The degree to which the reflection cites concrete evidence from the question or
answer, rather than using generic statements.
- 2 (Highly Specific): The reflection pinpoints specific facts, reasoning steps, or knowledge components. (e.g., ”My confi-
dence stems from citing the ’Second Law of Thermodynamics’ correctly,” or ”My uncertainty is due to vagueness on the
exact birth year of ’Alexander the Great’.”)
- 1 (Moderately Specific): The reflection refers to general areas without precision. (e.g., ”The reasoning process might not
be rigorous.”)
- 0 (Generic): The reflection uses boilerplate or vague phrases. (e.g., ”This is a complex question,” or ”My knowledge may
be limited.”)

### 3. Rationale Plausibility (Score: 0-2): 
Definition: The credibility and relevance of the reasons provided in the reflection.
- 2 (Highly Plausible): The stated reasons are highly convincing and directly relevant to the answer’s actual quality. For a
poor answer, it correctly identifies a known difficulty; for a good answer, it highlights a valid strength.
- 1 (Moderately Plausible): The reasoning is somewhat acceptable but feels slightly contrived or is not the most critical
factor.
- 0 (Implausible): The reasoning is unfounded, irrelevant, or logically flawed.

## Output Specification:
Your output must be a single JSON object with no additional text. The object should contain the scores for each of the three
dimensions, along with a total score calculated as the average of the three.
{{
"consistency score": 0-2 integer,
"specificity score": 0-2 integer,
"rationale plausibility score": 0-2 integer,
"total score": (sum of scores) / 3
}}
"""
