# Model parameters
model_name_or_path: "/your/model/path"
model_revision: main
torch_dtype: bfloat16
lora_r: 128
lora_alpha: 256
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: "/your/output/path"

# Training parameters
max_steps: 40
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-6
lr_scheduler_type: cosine
warmup_ratio: 0.03
seed: 42

# GRPO algorithm parameters
beta: 0.001
optim: adamw_8bit
max_prompt_length: 256
max_completion_length: 2048
num_generations: 8
use_vllm: true
vllm_gpu_memory_utilization: 0.3
generation_kwargs: {}  # Additional generation parameters

# Logging parameters
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 20
resume_from_checkpoint: false
report_to: tensorboard


# Custom config file path
custom_config_file: "./configs/grpo_custom_config.yaml"